# Autolab - autograding docker image

FROM ubuntu:18.04
MAINTAINER Honglei Zhang <zhanghonglei1997@gmail.com>
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
&& sed -i s@/archive.ubuntu.com/@/mirror.tuna.tsinghua.edu.cn/@g /etc/apt/sources.list \
&& sed -i s@/security.ubuntu.com/@/mirror.tuna.tsinghua.edu.cn/@g /etc/apt/sources.list

RUN apt-get update && apt-get install -y \
    apt-utils \
	gcc-multilib \
    make \
    build-essential \
    python2.7 \
    valgrind 3.2.1 \
    bsdmainutils \
    diffutils \
    curl \
    tcl8.5 \
    tcl \
    tcl8.5-dev \
    tcl-dev \
    tk8.5-dev \
    tk-dev \
    tk8.5 \
    tk \
    bison \
    flex \
    git \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*  \
&& dpkg-reconfigure -f noninteractive tzdata 

# Install autodriver
WORKDIR /home
RUN useradd autolab \ 
&& useradd autograde \
&& mkdir autolab autograde output mount \
&& chown autolab:autolab autolab \
&& chown autolab:autolab output \
&& chown autograde:autograde autograde

RUN git clone https://github.com/autolab/Tango.git
WORKDIR Tango/autodriver
RUN make clean && make \
&& cp autodriver /usr/bin/autodriver \
&& chmod +s /usr/bin/autodriver

# Clean up
WORKDIR /home
RUN apt-get remove -y git

RUN apt-get -y autoremove \
&& rm -rf Tango/

# Check installation
RUN ls -l /home \
&& which autodriver
